import { useState } from 'react'
import { X, FolderOpen, Download } from 'lucide-react'
import { useChat } from '../contexts/ChatContext'
import SessionFilesView from './SessionFilesView'
import AllFilesView from './AllFilesView'

const FileManagerPanel = ({ isOpen, onClose }) => {
  const { sessionFiles, downloadFile, deleteFile, taggedFiles, toggleFileTag } = useChat()
  const [activeTab, setActiveTab] = useState('session')

  const downloadAllFiles = () => {
    if (sessionFiles.total_files === 0) {
      alert('No files to download')
      return
    }

    // For now, show a confirmation and download each file individually
    // In a real implementation, we'd create a zip file
    if (confirm(`Download all ${sessionFiles.total_files} files? This will download each file individually.`)) {
      sessionFiles.files.forEach((file, index) => {
        // Add a small delay between downloads to avoid overwhelming the browser
        setTimeout(() => {
          downloadFile(file.filename)
        }, index * 100)
      })
    }
  }

  if (!isOpen) return null

  return (
    <div 
      className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50"
      onClick={onClose}
    >
      <div 
        className="bg-gray-800 rounded-lg shadow-xl max-w-4xl w-full max-h-[80vh] mx-4 flex flex-col"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b border-gray-700 flex-shrink-0">
          <div className="flex items-center gap-2">
            <FolderOpen className="w-6 h-6 text-blue-400" />
            <h2 className="text-xl font-semibold text-gray-100">File Manager</h2>
          </div>
          <div className="flex items-center gap-2">
            {sessionFiles.total_files > 0 && (
              <button
                onClick={downloadAllFiles}
                className="p-2 rounded-lg bg-blue-600 hover:bg-blue-700 transition-colors text-white"
                title="Download All Files"
              >
                <Download className="w-5 h-5" />
              </button>
            )}
            <button
              onClick={onClose}
              className="p-2 rounded-lg bg-gray-700 hover:bg-gray-600 transition-colors"
            >
              <X className="w-6 h-6" />
            </button>
          </div>
        </div>

        {/* Tabs */}
        <div className="flex border-b border-gray-700 flex-shrink-0">
          <button
            onClick={() => setActiveTab('session')}
            className={`px-6 py-3 text-sm font-medium transition-colors ${
              activeTab === 'session'
                ? 'border-b-2 border-blue-500 text-blue-400'
                : 'text-gray-400 hover:text-gray-200'
            }`}
          >
            Session Files ({sessionFiles.total_files})
          </button>
          <button
            onClick={() => setActiveTab('library')}
            className={`px-6 py-3 text-sm font-medium transition-colors ${
              activeTab === 'library'
                ? 'border-b-2 border-blue-500 text-blue-400'
                : 'text-gray-400 hover:text-gray-200'
            }`}
          >
            File Library
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto custom-scrollbar p-6 min-h-0">
          {activeTab === 'session' ? (
            <SessionFilesView
              files={sessionFiles}
              onDownloadFile={downloadFile}
              onDeleteFile={deleteFile}
              taggedFiles={taggedFiles}
              onToggleFileTag={toggleFileTag}
            />
          ) : (
            <AllFilesView />
          )}

          {/* Info Section */}
          {activeTab === 'session' && (
            <div className="mt-6 p-4 bg-gray-700/50 rounded-lg border border-gray-600">
              <h3 className="text-sm font-medium text-gray-200 mb-2">About Session Files</h3>
              <div className="text-xs text-gray-400 space-y-2">
                <p>
                  This panel shows all files in your current chat session, including:
                </p>
                <ul className="list-disc list-inside space-y-1 ml-2">
                  <li>Files you've uploaded</li>
                  <li>Files generated by tools</li>
                  <li>Data exports and reports</li>
                  <li>Code snippets and plots</li>
                </ul>
                <p className="pt-2 border-t border-gray-600">
                  Files are automatically organized by type and persist throughout your session.
                </p>
              </div>
            </div>
          )}

          {activeTab === 'library' && (
            <div className="mt-6 p-4 bg-gray-700/50 rounded-lg border border-gray-600">
              <h3 className="text-sm font-medium text-gray-200 mb-2">About File Library</h3>
              <div className="text-xs text-gray-400 space-y-2">
                <p>
                  This shows all files across all your sessions, including:
                </p>
                <ul className="list-disc list-inside space-y-1 ml-2">
                  <li>Files from previous sessions</li>
                  <li>Historical uploads and generated files</li>
                  <li>Search and filter capabilities</li>
                  <li>Load files into current session</li>
                </ul>
                <p className="pt-2 border-t border-gray-600">
                  Use the search and filters above to find specific files.
                </p>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}

export default FileManagerPanel
