"""Artifact discovery + base64 + MIME packaging.

After every ``python`` call we walk the workspace, compare each file's
mtime to the snapshot we took before the call, and package any new or
modified files into v2 artifacts (``{name, b64, mime, size, viewer}``).

A per-artifact size cap prevents inlining huge files into the websocket
frame; oversized files are listed as references for the user to fetch
explicitly via ``download_file``.
"""

from __future__ import annotations

import base64
import os
from pathlib import Path
from typing import Any, Dict, List, Tuple


_MIME = {
    ".png": ("image/png", "image"),
    ".jpg": ("image/jpeg", "image"),
    ".jpeg": ("image/jpeg", "image"),
    ".gif": ("image/gif", "image"),
    ".svg": ("image/svg+xml", "image"),
    ".webp": ("image/webp", "image"),
    ".html": ("text/html", "html"),
    ".htm": ("text/html", "html"),
    ".py": ("text/x-python", "code"),
    ".txt": ("text/plain", "code"),
    ".md": ("text/markdown", "code"),
    ".json": ("application/json", "code"),
    ".csv": ("text/csv", "code"),
    ".tsv": ("text/tab-separated-values", "code"),
    ".yaml": ("application/yaml", "code"),
    ".yml": ("application/yaml", "code"),
    ".pdf": ("application/pdf", "auto"),
    ".xlsx": (
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "auto",
    ),
    ".parquet": ("application/vnd.apache.parquet", "auto"),
}


def mime_for(path: str) -> Tuple[str, str]:
    ext = os.path.splitext(path)[1].lower()
    return _MIME.get(ext, ("application/octet-stream", "auto"))


def snapshot_mtimes(workspace: Path) -> Dict[str, float]:
    """Map of relative-path -> mtime for every file in the workspace."""
    workspace = workspace.resolve()
    out: Dict[str, float] = {}
    for root, _, files in os.walk(workspace):
        for name in files:
            full = Path(root) / name
            try:
                rel = str(full.relative_to(workspace))
                out[rel] = full.stat().st_mtime
            except OSError:
                continue
    return out


def diff_artifacts(
    workspace: Path,
    *,
    before: Dict[str, float],
    artifact_cap_bytes: int,
) -> List[Dict[str, Any]]:
    """Return v2 artifact dicts for files added or modified since ``before``.

    Sizes are checked via ``stat()`` *before* reading so an oversize file
    never gets fully loaded into memory.
    """
    workspace = workspace.resolve()
    after = snapshot_mtimes(workspace)
    artifacts: List[Dict[str, Any]] = []
    for rel, mtime in sorted(after.items()):
        if before.get(rel) == mtime:
            continue
        full = workspace / rel
        try:
            size = full.stat().st_size
        except OSError:
            continue
        mime, viewer = mime_for(rel)
        if size > artifact_cap_bytes:
            artifacts.append({
                "name": rel,
                "size": size,
                "mime": mime,
                "viewer": viewer,
                "description": (
                    f"Generated file (too large to inline: {size} bytes "
                    f"> cap {artifact_cap_bytes}); use download_file to fetch"
                ),
                "oversize": True,
            })
            continue
        try:
            data = full.read_bytes()
        except OSError:
            continue
        artifacts.append({
            "name": rel,
            "b64": base64.b64encode(data).decode("ascii"),
            "mime": mime,
            "size": len(data),
            "viewer": viewer,
            "description": f"Generated by code execution: {rel}",
        })
    return artifacts


def pick_primary(artifacts: List[Dict[str, Any]]) -> str | None:
    """Prefer the first image; fall back to the first artifact."""
    for art in artifacts:
        if art.get("viewer") == "image":
            return art["name"]
    return artifacts[0]["name"] if artifacts else None
