apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-logs-pvc"
  namespace: {{ .Release.Namespace }}
  annotations:
  {{- with .Values.persistence.logs.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.logs.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.logs.size | quote }}
  {{- if .Values.persistence.logs.storageClassName}}
  storageClassName: {{ .Values.persistence.logs.storageClassName | quote }}
  {{- end }}
